# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: PRINT NODE VERSION
        run: node --version

      - name: PRINT NPM VERSION
        run: npm --version

      - name: INSTALLING NPM PKGs
        run: npm install --ignore-scripts 

      - name: PRINT CURR DIR CONTENT
        run: ls -ltr

      - name: REMOVING node_modules directory
        run: rm -rf node_modules/

      - name: PRINT CURR DIR CONTENT
        run: ls -ltr